### ISSUE TITLE
render_elements == ""

### ISSUE THREAD

**Issue by chiperific** [AlchemyCMS/alchemy-guides#179]
After creating a page and fleshing out some elements, I can't get them to show in the front end.

The elements are visible in the preview window in the admin portal.
The page is published and not restricted

`render_elements` returns `""`
`@page.elements` returns `#<ActiveRecord::Associations::CollectionProxy []>`
`@page.fixed_elements` returns `#<ActiveRecord::Associations::CollectionProxy []>`

The page_layout partial renders, but no elements render.

Vanilla Rails 6 install with:

```
gem 'alchemy_cms', '~> 6.0'
gem 'alchemy-devise', '~> 6.0'
```

Simple ymls:
```
# config/alchemy/page_layouts.yml
...
- name: home
  unique: true
  elements: [hero, banner, three_column_gallery]
  autogenerate: [hero, banner, three_column_gallery]
...


# config/alchemy/elements.yml
...
- name: hero
  hint: true
  message: Hero block with bacground image, headline byline
  contents:
    - name: background_image
      type: EssencePicture
    - name: headline
      type: EssenceRichtext
      as_element_title: true
    - name: byline
      type: EssenceRichtext
  nestable_elements:
    - button
    - link
    - picture
    - icon
    - line


- name: banner
  hint: true
  message: A banner of large text, with optional background image
  contents:
    - name: background_image
      type: EssencePicture
    - name: text
      type: EssenceRichtext
  nestable_elements:
    - button
    - link
    - title
    - line
    - paragraph

- name: three_column_gallery
  hint: true
  message: a section with 3 columns
  nestable_elements:
    - column
...
```

I generated all the partials and confirmed they are rendering:
```
-# app/views/layouts/application.html.haml
!!!
%html{ lang: @page.language_code }
  %head
    = render 'alchemy/pages/meta_data'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %h1 Application
    = yield
    = render 'alchemy/edit_mode'
```

```
-# app/views/alchemy/page_layouts/_home.html.haml
%h1 Home
= render_elements
```

And these seem to be working:

```
>> @page.layout_display_name
=> "home"
>> @page.element_definition_names
=> ["hero", "banner", "three_column_gallery"]
```

What am I missing?
